{
 "title": "NCPA Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "{\"find\": \"terms\", \"field\": \"host.keyword\"}"
   },
   {
    "name": "iface",
    "label": "Interface",
    "query": "{\"find\": \"terms\", \"field\": \"name.keyword\",\"query\":\"type:interface AND NOT name.keyword:lo\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network OUT KB/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:288",
         "fake": true,
         "field": "host.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:279",
         "fake": true,
         "field": "name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:263",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:261",
         "field": "bytes_sent",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "type:interface AND NOT name.keyword:lo AND host.keyword:$host AND name.keyword:$iface",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Network IN KB/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:288",
         "fake": true,
         "field": "host.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:279",
         "fake": true,
         "field": "name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:263",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:261",
         "field": "bytes_recv",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "type:interface AND NOT name.keyword:lo AND host.keyword:$host AND name.keyword:$iface",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host: Disk used %",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "repeat": "host",
     "targets": [
      {
       "alias": "{{name.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:242",
         "fake": true,
         "field": "name.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:116",
         "fake": true,
         "field": "host.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:100",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:98",
         "field": "used_percent",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "type:disk_logical AND host.keyword: $host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$host: Disk used %",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "alias": "{{name.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:242",
         "fake": true,
         "field": "name.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:116",
         "fake": true,
         "field": "host.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:100",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:98",
         "field": "used_percent",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "type:disk_logical AND host.keyword: $host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$host: Disk used %",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "alias": "{{name.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:242",
         "fake": true,
         "field": "name.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:116",
         "fake": true,
         "field": "host.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:100",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:98",
         "field": "used_percent",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "type:disk_logical AND host.keyword: $host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Read KB/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:8920",
         "fake": true,
         "field": "name.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:8905",
         "fake": true,
         "field": "host.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:8893",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:8891",
         "field": "read_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "type: disk_physical AND host.keyword: $host AND name:sd?",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Write KB/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:8920",
         "fake": true,
         "field": "name.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:8905",
         "fake": true,
         "field": "host.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:8893",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:8891",
         "field": "write_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "type: disk_physical AND host.keyword: $host AND name:sd?",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:9475",
       "fake": true,
       "field": "host.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:9460",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:9312",
       "field": "percent",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "type:cpu AND host.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "gauge",
   "description": "Available memory (free + cached)",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:9475",
       "fake": true,
       "field": "host.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:9460",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:9312",
       "field": "available_percent",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "type:memory AND name:virtual AND host.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3323",
       "fake": true,
       "field": "pid",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:5819",
       "fake": true,
       "field": "host.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:3091",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3089",
       "field": "cpu_percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "type:process AND host.keyword:$host",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}